language: java
jdk: oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test

deploy:
 provider: script
 script: sh ./deployCleverCloud.sh
on:
 branch:master

addons:
  sonarcloud:
    organization: "eriwyr-github"
    token:
      secure: "pRkzcXrZuma8evr0Uyx+PCOjLTujRXfz1ecIJIi56QLy5CD7TEKtSCID6SGjmkEdm7koD43wo0iylM3yQQHSRc0bSYkixYXo1RIEsRevHDe6iIVd/ATEawpL/sf4Rm49gAR5bZkGu19hCTwi0tb9PObgTC4+p9iZ8h9Pjagu0My2DIcdmP/ZpuJd+ZjH1ZwxWgqQtmRnuslTQnUCVK7RBWRUZPNhqI35jlNBV4OJpQvivkT8G9TlAS0dhgf2dWFVu65480Vii8LLlmWoc/VXpD4Xpc4SJi1GJdIzipz5avhanCTDw36hfuVntwIbOWvVTUxumC6ACLLgc3ekwL9F/FmkjewGgE0A8+p49qkWevFF0R4e5G+TLAbcPY0VNAvsF8FBMMUIkK/lF27OQgxjtSXbMZKCQ7dzQJm7eas/WNweFoAD9IOC4tUJdmSU5giycgs4E8plVGxmvhQQaA5aKPLVzYKJSfIZY020ozcoJg1dCealkYXsF8JXgEXXfr0RZhNswo507WNiXbLjpWRe3tAyUh30mvDg1tD6/7shtILZNNW5jMnCATmJQ8qFmGpKkVfWAtCV81CghILoIZQQVj9A+xp48rF+SDEbTHN2iUf6SQ8HmlGLCBT3LoA7szUSqdbSRUlazLPjBcOjiYcwnm26DD1Im5VEyr+gATqmnQI="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar  -Dsonar.host.url=https://sonarcloud.io

notifications:
  email:
    recipients:
      - chabrier.valentin@gmail.com
      - maxencebernier@hotmail.fr
      - clasenkristoffer@gmail.com
  slack:
    rooms:
      - secure : GP2MVaJYuDZNZm+xQVYMWstzIGrgSni0oL1cRmRqf8icFCyHITLg2DK78GijO1ZAGHkzsvwPyisz33f+6eJ9PLG0dYFGbtfRLDHMT6Y6lMgosh9lpcCDwZGtf77Txo/mQZTBiTe7VsM2hAjvZSueCXghg97KIOypTq7JFWxznh4rCv5imKqRd34ixFM/gJzMVDiR2I+Zbw4uknwR+dWWkjSYwDQFe6eU05roCX2LZe1HQaaWQ6FHqgpaHuCBAwszZMD1XOq4s3z7wNhnluHNdXeSg4Zmua3bQD+CiN5421elZ1XdzGB2YBxb0szb/gHpwI+r1amOIn0781LNNbpctxRW1ZziAmcrS7aIhXUbwrswcLz3htvZHTNQBrix0m9OQni9rmrP6FFeMvCnq/Wm3YEBpO4e++cYMrymI7SLFTDBNtiVouunR5SZP+HxFxIqO2DbWehNyUZAOjnLxcsV8Dj97EWAj7Rf1QJ9sp7Iiz8FEFyZ2DPmP8tKM9AqcdufZgWXeVCG0C6jlWkqrJF29G6ZVkO5DniNm7y5R7pVSCb2STGFcRj3upYFz35XBzuZBGLG1K063zbNuT7VBfYqGp4lYb4nhlkVD0/inBQp6eMFXrZP5eJ1MjZNgsORM/4b0LiOfyUErTO4dyjMWrwrumUaWCqASCp4OQt2j7PYsWA=
    on_success: always
    on_failure: always
    template : 
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

cache:
  directories:
  - .autoconf
  - $HOME/.m2

addons:
 ssh_known_hosts:
 - push-par-clevercloud-customers.services.clever-cloud.com
