

language: java
jdk: oraclejdk8
dist: trusty

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "eriwyr-github"
script: 
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectName=polytech-cloud -Dsonar.projectKey=com.polytech-cloud:polytech-cloud:master -Dsonar.branch=master