language: java
jdk: oraclejdk8
dist: trusty

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "berniermaxence-github"
    token:
      secure: b7dd8598941ea856129f8aa543ec2e19d4b9f596 # encrypted value of your token
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io