language: java
jdk: oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "eriwyr-github"
    token:
      secure: "oRa4N6wzs+fQuzbA1wz93qXbEnLFFXYxBM+pBhjvHKgRDcLK6/Sa3kQ6nhJrWxAybgZFenS0nCnCBRN0r2JFp13hiGzb8RJ8Etkntq05UM6OvdwgI7dxrieqbKE4LJVMBkaceBP6AIDIiKYpH/AYK34cwBkqTfBYmr3r2Ek1lhkzfo+LTBfwxs8aqLHxA6H/Go35AD7tr1CyuFinxP10BYRQsqAqO2bhwMuE5Mv0saQjr5ddo/tb1xFsrIX/gFiRv9JHwfppnRuT+TETRp3FR2wY+mtGhMhRi0XFmMzKlPZmFAg39r6RB8ai8FPil/d6OMUs14tJhuO8fGQkmux4DelpvJenMUu1741j2+nptfra6rFccqkswM6D/pnyQXgF7JFgB5dQa52TO/gnqtT9zEpRzDoBFUPBGriHCY/1LfeTkb7TIfw+AF3XxMCGj7yiQXpLec3sPSRYwMfjqNbdzAEt7GXqrskRA5EItL1L8U8biQtYxBJ/YeT2NOSIuwppY8ptH5BbR/6Au2gP1WFA8OXCRK+NLb9X41Drmuxcly7EaWMERQoqy5TIY0nfcZl4P0E/A33h1tHdeErmn+mCVjdDXN2ZLZuT83rKb8H6UYVu+22fESUdKZYblCakgH4uP1X+L3cFMzhKSh3ou6jC7351wM8ZuQ3i1qar2+tAgdo="
script:
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar  -Dsonar.host.url=https://sonarcloud.io -Dsonar. 

deploy:
 provider: script
 script: sh ./deployCleverCloud.sh
on:
 branch:master

notifications:
  email:
    recipients:
      - chabrier.valentin@gmail.com
      - maxencebernier@hotmail.fr
      - clasenkristoffer@gmail.com
  slack:
    rooms:
      - secure : GP2MVaJYuDZNZm+xQVYMWstzIGrgSni0oL1cRmRqf8icFCyHITLg2DK78GijO1ZAGHkzsvwPyisz33f+6eJ9PLG0dYFGbtfRLDHMT6Y6lMgosh9lpcCDwZGtf77Txo/mQZTBiTe7VsM2hAjvZSueCXghg97KIOypTq7JFWxznh4rCv5imKqRd34ixFM/gJzMVDiR2I+Zbw4uknwR+dWWkjSYwDQFe6eU05roCX2LZe1HQaaWQ6FHqgpaHuCBAwszZMD1XOq4s3z7wNhnluHNdXeSg4Zmua3bQD+CiN5421elZ1XdzGB2YBxb0szb/gHpwI+r1amOIn0781LNNbpctxRW1ZziAmcrS7aIhXUbwrswcLz3htvZHTNQBrix0m9OQni9rmrP6FFeMvCnq/Wm3YEBpO4e++cYMrymI7SLFTDBNtiVouunR5SZP+HxFxIqO2DbWehNyUZAOjnLxcsV8Dj97EWAj7Rf1QJ9sp7Iiz8FEFyZ2DPmP8tKM9AqcdufZgWXeVCG0C6jlWkqrJF29G6ZVkO5DniNm7y5R7pVSCb2STGFcRj3upYFz35XBzuZBGLG1K063zbNuT7VBfYqGp4lYb4nhlkVD0/inBQp6eMFXrZP5eJ1MjZNgsORM/4b0LiOfyUErTO4dyjMWrwrumUaWCqASCp4OQt2j7PYsWA=
    on_success: always
    on_failure: always
    template : 
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

cache:
  directories:
  - .autoconf
  - $HOME/.m2

addons:
 ssh_known_hosts:
 - push-par-clevercloud-customers.services.clever-cloud.com
