language: java
jdk: oraclejdk8
dist: trusty

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "eriwyr-github"
    token:
      secure: "IG/TgffiQzOi934xxdD3Nn8pchDklTZx9rLTr1iz6qhiQ83OG56iSp1iWbNaRYp9jFyWbFkNt/QxNxQH5KfVOKa3lx5a8AHhC0EmhNZKqqblLZKGcexVbuCbJN5atu0IV/HU+LPatkCJj1/TDEHITgYlMH6aQBMWMhzIiiZlAUqHymBSBgEaGlzcHUxm+buKoSEQAqdrXP3/3tST2Ifr9iOsYz5I2/XY6WkjMpl0XWddnVqPGj4X/YhFfzqua6A5s90zK4mp/T4w3MAqC/qh/y/9dX/bYHCZRhcWUruDiqva5Ke0OSc5vGdRqzrxdWnPlPlOe2UEvHKflXycLdlxxKwsG33WWxa+fuWcIkLzQ/4fN9g5Rjp0cCVx+EagSBiqBaCuL+MfBTow24YGVpCpOPZADVEW3uGJtZw2L8wWDYTU3zR3zgQn5kzzmCgb5XAXT8lHDwBXUw8mn2Yj38BsKqQGr+26669Yr+lJJWogGLqZHAv05XWLwdcUHpm0ROT9kwxQVWtwQ+ghf3XQQ1tQEgiqOWo4d1E1W5+2YxDtoddDdJkt6MwQ42W/gi9+SeyiyzTYMoRHchfSHh7FtNA3Xg9ZbX/f7DRQLLbEGze340sJ1LrUJ3Q/7D6EBd66Vh3BElDczYl4HC74oA3LcnkO2dgt+tzHMxod4q4IBcE4v5w="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io 

deploy:
 provider: script
 script: sh ./deployCleverCloud.sh
on:
 branch:master

notifications:
  email:
    recipients:
      - chabrier.valentin@gmail.com
      - maxencebernier@hotmail.fr
      - clasenkristoffer@gmail.com
  slack:
    rooms:
      - secure : GP2MVaJYuDZNZm+xQVYMWstzIGrgSni0oL1cRmRqf8icFCyHITLg2DK78GijO1ZAGHkzsvwPyisz33f+6eJ9PLG0dYFGbtfRLDHMT6Y6lMgosh9lpcCDwZGtf77Txo/mQZTBiTe7VsM2hAjvZSueCXghg97KIOypTq7JFWxznh4rCv5imKqRd34ixFM/gJzMVDiR2I+Zbw4uknwR+dWWkjSYwDQFe6eU05roCX2LZe1HQaaWQ6FHqgpaHuCBAwszZMD1XOq4s3z7wNhnluHNdXeSg4Zmua3bQD+CiN5421elZ1XdzGB2YBxb0szb/gHpwI+r1amOIn0781LNNbpctxRW1ZziAmcrS7aIhXUbwrswcLz3htvZHTNQBrix0m9OQni9rmrP6FFeMvCnq/Wm3YEBpO4e++cYMrymI7SLFTDBNtiVouunR5SZP+HxFxIqO2DbWehNyUZAOjnLxcsV8Dj97EWAj7Rf1QJ9sp7Iiz8FEFyZ2DPmP8tKM9AqcdufZgWXeVCG0C6jlWkqrJF29G6ZVkO5DniNm7y5R7pVSCb2STGFcRj3upYFz35XBzuZBGLG1K063zbNuT7VBfYqGp4lYb4nhlkVD0/inBQp6eMFXrZP5eJ1MjZNgsORM/4b0LiOfyUErTO4dyjMWrwrumUaWCqASCp4OQt2j7PYsWA=
    on_success: always
    on_failure: always
    template : 
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
 ssh_known_hosts:
 - push-par-clevercloud-customers.services.clever-cloud.com
