version: '2'
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - /Users/maxencebernier/Documents/polytech_5a/cloud/groupe_a_cloud_polytech/prometheus.yml:/etc/prometheus/prometheus.yml 
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    grafana:
            image: grafana/grafana
            volumes:
                - grafana_data:/var/lib/grafana
            environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
            depends_on:
                - prometheus
            ports:
                - "3000:3000"
volumes:
        prometheus_data: {}
        grafana_data: {}